Repository 42Heroes/42WLE-Front, pull requests merged in 2022-08, with the labels that each got.

#30 Main, Find, Chat, Board 수정
  components/board/CommentContent.tsx
  components/board/CommentList.tsx
  components/board/CreatePost.tsx
  components/board/EditPost.tsx
  components/board/PostCard.tsx
  components/chat/ActiveChat.tsx
  components/chat/ChatContent.tsx
  components/chat/ChatRoom.tsx
  components/chat/ChatRoomList.tsx
  components/common/Confirm.tsx
  components/common/Modal.tsx
  components/common/SocketEventProvider.tsx
  components/common/UserCard.tsx
  components/layout/Nav.tsx
  components/profile/Profile.tsx
  interfaces/board.interface.ts
  library/api/board.ts
  package.json
  pages/board.tsx
  pages/find.tsx
  pages/index.tsx
  styles/theme.ts
Labels: enhancement ✨, High 🥇

#28 WE-127-dev-refresh-token-으로-silent-refresh-실행
  library/api/login.ts
Labels: Medium 🥈

#29 WE-155 protect routing 처리
  components/auth/ProtectedPage.tsx
  components/common/LoadingIndicator.tsx
  components/layout/Nav.tsx
  hooks/useMe.ts
  pages/chat.tsx
  pages/login.tsx
  pages/mypage/edit.tsx
  pages/mypage/index.tsx
Labels: enhancement ✨, Medium 🥈

#31 WE-189 댓글 post, edit api call 두 번 발생 수정
  components/board/CommentContent.tsx
  components/board/CommentList.tsx
Labels: Bug 🚨, Medium 🥈

#32 WE-141 유저 모달 수정
  components/common/UserCard.tsx
  components/layout/Nav.tsx
  components/profile/Profile.tsx
  library/api/user.ts
  pages/find.tsx
  pages/index.tsx
  pages/login.tsx
Labels: Refactor 🌈, Medium 🥈

#33 WE-167 전체적으로 있어야하는 기능
  components/layout/LoginLayout.tsx
  components/layout/RegisterLayout.tsx
  hooks/useRegister.ts
  interfaces/user.interface.ts
  library/api/uploadFile.ts
  library/api/user.ts
  pages/api/s3/upload.ts
  pages/register/extra-info.tsx
  pages/register/introduction.tsx
  pages/register/learn.tsx
  pages/register/native.tsx
  pages/register/nickname.tsx
  pages/register/photo.tsx
  pages/register/preview.tsx
  recoil/atoms/userAtom.ts
Labels: enhancement ✨, Refactor 🌈, Medium 🥈

#34 포스트에 이미지 업로드 기능 추가, Find 페이지와 Chat 페이지 수정사항
  components/board/CommentContent.tsx
  components/board/CommentList.tsx
  components/board/CreatePost.tsx
  components/board/PostCard.tsx
  components/common/SocketEventProvider.tsx
  components/common/UserCard.tsx
  interfaces/board.interface.ts
  pages/board.tsx
  pages/chat.tsx
  pages/find.tsx
  pages/login.tsx
  pages/mypage/edit.tsx
Labels: Bug 🚨, enhancement ✨, High 🥇

#35 WE-225 회원가입 로그인
  components/layout/CommonLayout.tsx
  library/api/login.ts
  pages/auth/social.tsx
  pages/auth/social/42.tsx
  pages/register/photo.tsx
Labels: Refactor 🌈, Medium 🥈

#37 포스트 이미지 모달 생성 + 불필요한 import 삭제 + 타입에러 수정
  components/board/OriginalImage.tsx
  components/board/PostCard.tsx
  components/board/PostImage.tsx
  components/chat/ChatRoom.tsx
  components/chat/ChatRoomList.tsx
  components/common/Confirm.tsx
  components/common/Language.tsx
  components/common/Modal.tsx
  components/profile/Profile.tsx
  pages/find.tsx
  pages/index.tsx
  pages/mypage/edit.tsx
Labels: Bug 🚨, enhancement ✨, High 🥇

#40 WE-224 eslint 타입 검증
  components/chat/ChatInput.tsx
  components/socket/CallEventProvider.tsx
  library/api/axios-instance.ts
  pages/_document.tsx
  pages/playground.tsx
  pages/temp.tsx
Labels: High 🥇

#41 WE-237 turn server 적용합니다
  components/socket/CallEventProvider.tsx
Labels: Bug 🚨, High 🥇

#42 [Chat] 마지막 메시지 전송 시간 표시
  components/chat/ChatRoom.tsx
Labels: enhancement ✨, High 🥇

#43 [Chat] 채팅 전송시간 날짜 변경선 표시
  components/chat/ChatContent.tsx
Labels: enhancement ✨, High 🥇

#38 채팅 이미지 전송 기능 추가
  components/chat/ActiveChat.tsx
  components/chat/ChatContent.tsx
  components/chat/ChatInput.tsx
  components/chat/ChatRoom.tsx
Labels: enhancement ✨, High 🥇

#44 ChatContent 에러수정
  components/chat/ChatContent.tsx
  components/chat/ChatRoom.tsx
Labels: Bug 🚨

#45 send chat 에러 수정 및 레이아웃 수정
  components/chat/ChatInput.tsx
  components/chat/ChatRoomList.tsx
  pages/chat.tsx
Labels: Bug 🚨, High 🥇
