Repository 42Heroes/42WLE-Front, pull requests merged in 2022-10, with the labels that each got.

#46 [FIX] 게시판 페이지 레이아웃 변경
  components/board/CommentContent.tsx
  components/board/CommentList.tsx
  components/board/EditPost.tsx
  components/board/PostCard.tsx
  components/board/PostImage.tsx
  components/board/StartPost.tsx
  hooks/useToggle.tsx
  library/showCreatedAt.ts
  package-lock.json
  package.json
  yarn.lock
Labels: Bug 🚨, enhancement ✨, High 🥇

#48 Update README.md
  README.md
Labels: Docs 📝

#49 WE-258 통화 오버레이, 통화 유무에 따른 ui 디자인
  components/call/ActiveVideoCall.tsx
  components/call/CallOverlay.tsx
  components/chat/ActiveChat.tsx
  components/chat/ChatRoom.tsx
  components/layout/CommonLayout.tsx
  hooks/usePeerConnection.ts
  package.json
  pages/chat.tsx
  recoil/atoms/callAtom.ts
  yarn.lock
Labels: enhancement ✨

#47 WE-288-채팅-페이지-레이아웃-변경
  components/chat/ChatInput.tsx
  components/chat/ChatRoomList.tsx
Labels: enhancement ✨
