Repository 42Heroes/42WLE-Front, pull requests merged in 2022-05, with the labels that each got.

#3 [WE-102] 언어 데이터 생성
  library/languages.js
  public/languages/arabic.svg
  public/languages/bengali.svg
  public/languages/chinese.svg
  public/languages/dutch.svg
  public/languages/english.svg
  public/languages/finnish.svg
  public/languages/french.svg
  public/languages/german.svg
  public/languages/hindi.svg
  public/languages/italian.svg
  public/languages/japanese.svg
  public/languages/korean.svg
  public/languages/malay.svg
  public/languages/portuguese.svg
  public/languages/russian.svg
  public/languages/spanish.svg
  public/languages/swedish.svg
  public/languages/temp.json
  public/languages/thai.svg
  public/languages/turkish.svg
  public/languages/vietnamese.svg
Labels: Docs 📝

#4 WE-103-버튼-컴포넌트-생성
  components/common/Button.tsx
Labels: enhancement ✨

#7 WE-108 회원가입step-5
  pages/register/introduction.tsx
Labels: enhancement ✨

#6 WE-111 MSW
  .gitignore
  mocks/browser.ts
  mocks/handlers/index.ts
  mocks/handlers/user.ts
  mocks/index.ts
  mocks/node.ts
  package.json
  pages/_app.tsx
  public/mockServiceWorker.js
  yarn.lock
Labels: enhancement ✨, Medium 🥈

#8 WE-109-회원가입step-6
  .gitignore
  mocks/browser.ts
  mocks/handlers/index.ts
  mocks/handlers/user.ts
  mocks/index.ts
  mocks/node.ts
  package.json
  pages/_app.tsx
  pages/register/extra-info.tsx
  public/mockServiceWorker.js
  yarn.lock
Labels: enhancement ✨, Medium 🥈

#9 WE-110 회원가입step7
  components/common/Language.tsx
  components/profile/Profile.tsx
  pages/_app.tsx
  pages/register/preview.tsx
Labels: enhancement ✨, Medium 🥈

#10 WE-24 회원가입
  components/common/Button.tsx
  components/common/DragDrop.tsx
  components/common/FTLogo.tsx
  components/common/Language.tsx
  components/common/LanguageDropdown.tsx
  components/common/LanguageSelected.tsx
  components/common/Title.tsx
  components/layout/Header.tsx
  components/layout/Layout.tsx
  components/layout/LoginLayout.tsx
  components/layout/Nav.tsx
  components/profile/Profile.tsx
  hooks/useDragDrop.ts
  hooks/useInput.ts
  library/languages.js
  next.config.js
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/login.tsx
  pages/register/extra-info.tsx
  pages/register/introduction.tsx
  pages/register/learn.tsx
  pages/register/native.tsx
  pages/register/nickname.tsx
  pages/register/preview.tsx
  pages/register/profile-image.tsx
  public/42Logo.svg
  public/camera.svg
  public/fonts/JetBrainsMono/Bold.woff2
  public/fonts/JetBrainsMono/Regular.woff2
  public/worldMap.svg
  styles/Home.module.css
  styles/fonts.css
  styles/global.ts
  styles/globals.css
  styles/media.ts
  styles/openColor.ts
  styles/styled.d.ts
  styles/theme.ts
  yarn.lock
Labels: enhancement ✨, Medium 🥈

#13 WE-112 CommonLayout 생성
  components/layout/CommonLayout.tsx
  components/layout/Header.tsx
  components/layout/Layout.tsx
  components/layout/Nav.tsx
  pages/board.tsx
  pages/chat.tsx
  pages/find.tsx
Labels: enhancement ✨, High 🥇

#14 WE-119 user Recoil
  components/common/Auth.tsx
  library/user_atom.ts
  pages/_app.tsx
  pages/find.tsx
Labels: enhancement ✨, High 🥇

#15 WE-118 React-query 설정
  pages/_app.tsx
Labels: enhancement ✨

#16 WE-113 회원가입 통합
  components/common/Auth.tsx
  components/common/Button.tsx
  components/common/DragDrop.tsx
  components/common/FTLogo.tsx
  components/common/Language.tsx
  components/common/LanguageDropdown.tsx
  components/common/LanguageDropdownList.tsx
  components/common/LanguageSelected.tsx
  components/layout/LoginLayout.tsx
  components/profile/Profile.tsx
  hooks/useRegister.ts
  interfaces/user.interface.ts
  library/ImageConverter.ts
  library/languages.js
  library/languages.ts
  library/user_atom.ts
  library/utils.ts
  next.config.js
  package.json
  pages/find.tsx
  pages/index.tsx
  pages/login.tsx
  pages/register/extra-info.tsx
  pages/register/introduction.tsx
  pages/register/learn.tsx
  pages/register/native.tsx
  pages/register/nickname.tsx
  pages/register/photo.tsx
  pages/register/preview.tsx
  pages/register/profile-image.tsx
  public/42Logo.svg
  public/assets/icons/42Logo.svg
  public/assets/icons/camera.svg
  public/assets/icons/logo.svg
  public/assets/icons/user.svg
  public/assets/worldMap.svg
  recoil/atoms/index.ts
  recoil/atoms/userAtom.ts
  yarn.lock
Labels: enhancement ✨, Refactor 🌈, High 🥇

#17 WE-115 유저-카드
  components/common/UserCard.tsx
  interfaces/user_interfaces.tsx
  library/dummydata.js
  pages/_app.tsx
  pages/find.tsx
  recoil/atoms/userAtom.ts
Labels: enhancement ✨
